# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegapp', '0002_auto_20161020_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(default=True, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
