# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegapp', '0003_auto_20161026_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comentario',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
