# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegapp', '0005_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='horario_dias',
            field=models.CharField(default='Lunes a Domingo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='horario_horas',
            field=models.CharField(default='10:00 a 21:00', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sitioweb',
            field=models.CharField(default='www.sitio.com.mx', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telefono',
            field=models.CharField(default='81828345', max_length=20),
            preserve_default=False,
        ),
    ]
